* How to Use this Repo
This repo is a set of literate shell scripts and some plain old org files used to provision my computers. Each file is written in org mode with Babel and can run as a script.
* Tangling (Scriptifying) The Org Files
** Disciples of The Church of Emacs
Generate the file by opening the file in emacs and typing =M-x org-babel-tangle= or using the key combination =C-c C-v t=. Each generated scripted will appear in a =./generated-scripts= directory in the current working directory.
** Other UNIXersists
Since you probably do not have emacs installed, we can use the =sed= command to extricate and create =bash= files from =org= files.

The following code snippet will first isolate the bash code blocks and then delete the fencing around them, outputting the result to the =stdout=.

#+BEGIN_SRC sh
$ sed -n '/^#+BEGIN_SRC bash/,/^#+END_SRC/ p' < try-me.org | sed '/^#+BEGIN_SRC bash/d' | sed '/^#+END_SRC/ d'
#+END_SRC

You can output the resulting =stdout= to a file like so:

#+BEGIN_SRC sh
$ sed -n '/^#+BEGIN_SRC bash/,/^#+END_SRC/ p' < try-me.org | sed '/^#+BEGIN_SRC bash/d' | sed '/^#+END_SRC/ d' > try-me.sh
#+END_SRC

Or you can direct the output directly to the bash interpreter, which will run the file as a script:

#+BEGIN_SRC sh
$ sed -n '/^#+BEGIN_SRC bash/,/^#+END_SRC/ p' < try-me.org | sed '/^#+BEGIN_SRC bash/d' | sed '/^#+END_SRC/ d' | bash
#+END_SRC
* Current Systems
- Lenovo Thinkpad P50: Ubuntu 18.10 (Cosmic Cuttlefish)
* Table of Contents and Basic Order of Execution
** 1. The Basics
*** [[file:git.org][1.1 Git]]
It is very hard to do anything these days without installing and configuring git.
*** [[file:ssh.org][1.2 SSH]]
Installing and configuring ssh keys.
*** [[file:mobile-power-management.org][1.3 Mobile Power Management]]
Installing =tlp= and other battery saving utilities.
*** [[file:thinkpad.org][1.4 Thinkpad Specific Software]]
*** [[file:zsh.org][1.5 Installing ZSH and Oh My ZSH]]
*** [[file:shell-config.org][1.6 Symlinking .zshrc and .bashrc]]
** 2. Text Editors
*** [[file:emacs.org][2.1 Building and Installing Emacs]]
*** [[file:vscode.org][2.2 Visual Studio Code]]
** 3. Printing and Scanning
*** [[file:brother-dcp-7065dn.org][3.1 Brother DCP-7065DN]]
** 4. Applications
*** [[file:redshift.org][4.1 Redshift]]
Save your eyes from blue light.
*** [[file:riot-im.org][4.2 Riot IM]]
*** [[file:keybase.org][4.3 Keybase]]
*** [[file:pcloud.org][4.4 pCloud]]
*** [[file:signal.org][4.5 Signal]]
*** [[file:web-browsers.org][4.6 Web Browsers]]
** 5. Programming Environments
*** [[file:bash-env.org][5.1 Shell Script]]
*** [[file:rust-env.org][5.2 Rust]]

